# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password